name: $name
version: $version
main: com.moulberry.axiom.AxiomPaper
description: $description
authors:
  - Moulberry
api-version: "$apiVersion"
softdepend: ["CoreProtect", "ViaVersion", "WorldGuard", "PlotSquared"]
permissions:
  axiom.all:
    description: Allows use of ALL Axiom features. Same as /op. This permission bypasses all other permissions.
    default: op
  axiom.default:
    description: Allows the use of all Axiom features recommended for public servers
    children:
      axiom.use: true
      axiom.allow_copying_other_plots: true
      axiom.can_import_blocks: true
      axiom.can_export_blocks: true
      axiom.chunk.*: true
      axiom.build.*: true
      axiom.editor.*: true
      axiom.player.*: true
      axiom.world.*: true
      axiom.capability.*: true
      axiom.tool.*: true
      axiom.builder_tool.*: true

  # Non-default permissions (not recommended for public servers)
  axiom.entity.*:
    description: Permissions related to entities
    children:
      axiom.entity.spawn: true
      axiom.entity.manipulate: true
      axiom.entity.delete: true
      axiom.entity.request_data: true
  axiom.blueprint.*:
    description: Permissions related to blueprints
    children:
      axiom.blueprint.upload: true
      axiom.blueprint.request: true
      axiom.blueprint.manifest: true
  axiom.annotation.*:
    description: Permissions related to annotations
    children:
      axiom.annotation.create: true
      axiom.annotation.clear_all: true
  axiom.debug:
    description: Allows use of the /axiompaperdebug command

  # Default permissions (recommended for public servers)
  axiom.use:
    description: Allows basic use of axiom
  axiom.allow_copying_other_plots:
    description: If in a PlotSquared world, allow copying plots owned by other players
  axiom.can_import_blocks:
    description: Allow bringing builds into the server via blueprints, file menu, etc.
  axiom.can_export_blocks:
    description: Allow bringing builds out of the server via blueprints, file menu, etc.
  axiom.chunk.*:
    description: Permissions related to requesting chunk data from the server
    children:
      axiom.chunk.request: true
      axiom.chunk.request_block_entity: true
  axiom.build.*:
    description: Permissions related to placing blocks
    children:
      axiom.build.place: true
      axiom.build.section: true
      axiom.build.nbt: true
  axiom.editor.*:
    description: Permissions related to the Editor UI
    children:
      axiom.editor.use: true
      axiom.editor.views: true
  axiom.player.*:
    description: Permissions related to players manipulating themselves
    children:
      axiom.player.bypass_movement_restrictions: true
      axiom.player.speed: true
      axiom.player.teleport: true
      axiom.player.gamemode.*: true
      axiom.player.hotbar: true
      axiom.player.set_no_physical_trigger: true
  axiom.world.*:
    description: Permissions related to manipulating the world
    children:
      axiom.world.time: true
      axiom.world.property: true
  axiom.capability.*:
    description: Permissions associated with capabilities
    children:
      axiom.capability.bulldozer: true
      axiom.capability.replace_mode: true
      axiom.capability.force_place: true
      axiom.capability.no_updates: true
      axiom.capability.tinker: true
      axiom.capability.infinite_reach: true
      axiom.capability.fast_place: true
      axiom.capability.angel_placement: true
      axiom.capability.no_clip: true
      axiom.capability.phantom: true
  axiom.tool.*:
    description: Permissions associated with tools
    children:
      axiom.tool.magic_select: true
      axiom.tool.box_select: true
      axiom.tool.freehand_select: true
      axiom.tool.lasso_select: true
      axiom.tool.ruler: true
      axiom.tool.annotation: true
      axiom.tool.painter: true
      axiom.tool.noise_painter: true
      axiom.tool.biome_painter: true
      axiom.tool.gradient_painter: true
      axiom.tool.script_brush: true
      axiom.tool.freehand_draw: true
      axiom.tool.sculpt_draw: true
      axiom.tool.rock: true
      axiom.tool.weld: true
      axiom.tool.melt: true
      axiom.tool.stamp: true
      axiom.tool.text: true
      axiom.tool.shape: true
      axiom.tool.path: true
      axiom.tool.modelling: true
      axiom.tool.floodfill: true
      axiom.tool.fluidball: true
      axiom.tool.elevation: true
      axiom.tool.slope: true
      axiom.tool.smooth: true
      axiom.tool.distort: true
      axiom.tool.roughen: true
      axiom.tool.shatter: true
      axiom.tool.extrude: true
      axiom.tool.modify: true
  axiom.builder_tool.*:
    description: Permissions associated with tools
    children:
      axiom.builder_tool.move: true
      axiom.builder_tool.clone: true
      axiom.builder_tool.stack: true
      axiom.builder_tool.smear: true
      axiom.builder_tool.ruler: true
      axiom.builder_tool.extrude: true
      axiom.builder_tool.erase: true
      axiom.builder_tool.setup_symmetry: true
