name: $name
version: $version
main: com.moulberry.axiom.AxiomPaper
description: $description
authors:
  - Moulberry
api-version: "$apiVersion"
softdepend: ["CoreProtect"]
permissions:
  axiom.*:
    description: Allows use of all default Axiom features
    default: op
  axiom.debug:
    description: Allows use of the /axiompaperdebug command
    default: op
  axiom.entity.*:
    description: Allows use of all entity-related features (spawning, manipulating, deleting)
    default: op
  axiom.entity.spawn:
    description: Allows entity spawning
  axiom.entity.manipulate:
    description: Allows entity manipulation
  axiom.entity.delete:
    description: Allows entity deletion

  axiom.allow_copying_other_plots:
    description: This permission allows users to copy other user's plots
    default: true
  axiom.can_import_blocks:
    description: Allows players to import schematics/blueprints into Axiom
    default: true
